name: firebase_cluster
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  cloud_firestore: ^5.3.0
  firebase_analytics: ^11.3.0

  needle:
    path: ../needle

  picasso:
    path: ../picasso

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2