name: monitoring
description: Unicode apps monitoring solution
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  picasso:
    path: ../picasso

  firebase_cluster:
    path: ../firebase_cluster

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
